ritp_agents_imitation_objective:
  _target_: nuplan_zigned.training.modeling.objectives.qcmae_agents_imitation_objective.AgentsImitationObjective
  _convert_: 'all'
  name: agent_imitation_objective
  weight: 1.
  output_dim: ${model.qcmae_model_params.output_dim}
  output_head: ${model.qcmae_model_params.output_head}
  num_past_steps: ${model.qcmae_feature_params.past_trajectory_sampling.num_poses}
  self_distillation: false
  sd_temperature: null
  sd_alpha: null
  pretrain: false
  pretrain_map_encoder: false
  pretrain_agent_encoder: false
  prob_pretrain_mask: null
  prob_pretrain_mask_mask: null
  prob_pretrain_mask_random: null
  prob_pretrain_mask_unchanged: null
  only_ego: false