ritp_actor_objective:
  _target_: nuplan_zigned.training.modeling.objectives.ritp_actor_objective.ActorObjective
  _convert_: 'all'
  output_dim: ${model.qcmae_model_params.output_dim}
  output_head: ${model.qcmae_model_params.output_head}
  num_past_steps: ${model.qcmae_feature_params.past_trajectory_sampling.num_poses}
  only_ego: false
