minAHE:
  _target_: nuplan_zigned.training.modeling.metrics.qcmae_agents_imitation_metrics.minAHE
  _convert_: 'all'
  output_dim: ${model.model_params.output_dim}
  output_head: ${model.model_params.output_head}
  num_past_steps: ${model.feature_params.past_trajectory_sampling.num_poses}
  num_future_steps: ${model.target_params.future_trajectory_sampling.num_poses}
  num_modes: ${model.model_params.num_modes}
  self_distillation: ${model.model_params.self_distillation}
  only_evaluate_av: True
  num_modes_eval: ${model.model_params.num_modes}