minADE:
  _target_: nuplan_zigned.training.modeling.metrics.qcmae_agents_imitation_metrics.minADE
  _convert_: 'all'
  output_dim: ${model.qcmae_model_params.output_dim}
  output_head: ${model.qcmae_model_params.output_head}
  num_past_steps: ${model.qcmae_feature_params.past_trajectory_sampling.num_poses}
  num_future_steps: ${model.qcmae_target_params.future_trajectory_sampling.num_poses}
  num_modes: ${model.qcmae_model_params.num_modes}
  self_distillation: false
  only_evaluate_av: ${model.ritp_planner_model_params.only_evaluate_av}
  num_modes_eval: ${model.qcmae_model_params.num_modes}