_target_: nuplan_zigned.training.modeling.models.qcmae.QCMAE
_convert_: 'all'
model_name: qcmae
model_params:
  _target_: nuplan_zigned.training.modeling.models.qcmae.ModelParams
  _convert_: 'all'
  input_dim: 2
  hidden_dim: 64
  output_dim: 2
  output_head: False  # whether the model output heading. if False, heading will be estimated by arctan(dy/dx)
  num_past_steps: ${model.feature_params.past_trajectory_sampling.num_poses}
  num_future_steps: ${model.target_params.future_trajectory_sampling.num_poses}
  num_modes: 6
  num_recurrent_steps: 4
  num_freq_bands: 64
  num_map_layers: 1
  num_agent_layers: 1
  num_dec_layers: 1
  num_heads: 8
  head_dim: 16
  dropout: 0.1
  pl2pl_radius: 150
  time_span: 10
  pl2a_radius: 50
  a2a_radius: 50
  num_t2m_steps: 30
  pl2m_radius: 150
  a2m_radius: 150
  self_distillation: False
  sd_temperature: 0.5
  sd_alpha: 1.5
  sd_margin: 50
  pretrain: False
  pretrain_map_encoder: False
  pretrain_agent_encoder: True
  prob_pretrain_mask: [0.3, 0.3]
  prob_pretrain_mask_mask: 0.8
  prob_pretrain_mask_random: 0.1
  prob_pretrain_mask_unchanged: 0.1
  pretrained_model_dir: null
  ckpt_path: null
  gpus: ${lightning.trainer.params.gpus}

# Params for features
feature_params:
  _target_: nuplan_zigned.training.modeling.models.qcmae.FeatureParams
  _convert_: 'all'
  # Map features
  dim: 3
  num_past_steps: ${model.feature_params.past_trajectory_sampling.num_poses}
  num_future_steps: ${model.target_params.future_trajectory_sampling.num_poses}
  radius: 150
  map_features: [LANE, LEFT_BOUNDARY, RIGHT_BOUNDARY, STOP_LINE, CROSSWALK, ROUTE_LANES]
  max_elements:
    LANE: 30
    LEFT_BOUNDARY: 30
    RIGHT_BOUNDARY: 30
    STOP_LINE: 20
    CROSSWALK: 20
    ROUTE_LANES: 30
  max_points:
    LANE: 20
    LEFT_BOUNDARY: 20
    RIGHT_BOUNDARY: 20
    STOP_LINE: 20
    CROSSWALK: 20
    ROUTE_LANES: 20
  predict_unseen_agents: False
  vector_repr: True
  interpolation_method: linear
  # Agent features
  agent_features: [VEHICLE, PEDESTRIAN, BICYCLE, TRAFFIC_CONE, BARRIER, CZONE_SIGN, GENERIC_OBJECT]
  max_agents:
    VEHICLE: 30
    PEDESTRIAN: 30
    BICYCLE: 30
    TRAFFIC_CONE: 30
    BARRIER: 30
    CZONE_SIGN: 30
    GENERIC_OBJECT: 10
  # Parameters for past trajectory
  past_trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    num_poses: 49      # target past poses
    time_horizon: 4.9  # [s] time horizon of future poses

# Params for targets
target_params:
  _target_: nuplan_zigned.training.modeling.models.qcmae.TargetParams
  _convert_: 'all'
  agent_featrues: [VEHICLE, PEDESTRIAN, BICYCLE]
  num_past_steps: ${model.feature_params.past_trajectory_sampling.num_poses}
  # Parameters for predicted trajectory
  future_trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    num_poses: 80      # target future poses
    time_horizon: 8.0  # [s] time horizon of future poses

