_target_: nuplan_zigned.training.modeling.models.ritp_planner.RITPPlanner
_convert_: 'all'
model_name: ritp_planner
ritp_planner_model_params:
  _target_: nuplan_zigned.training.modeling.models.ritp_planner.RITPPlannerModelParams
  _convert_: 'all'
  num_imagined_experiences: null
  imagine_batch_size: null
  imagine_max_elements: 300
  imagine_max_agents:
    VEHICLE: 50
    PEDESTRIAN: null
    BICYCLE: null
    TRAFFIC_CONE: null
    BARRIER: null
    CZONE_SIGN: null
    GENERIC_OBJECT: 10
  finetune_mode: pseudo_ground_truth  # 'pseudo_ground_truth', 'critic'
  finetune_range: full  # finetune range when RL. can be 'full', 'decoder', 'refine_module', 'additional_refine_module', 'mlp'.
  only_evaluate_av: False  # True: only evaluate AV. False: only evaluate AV VEHICLE, PEDESTRIAN, and BICYCLE.
  num_rl_workers: ???
  # TD3 params
  discount: 0.99
  tau: 0.005  # should be 0.005 * num_rl_workers？
  expl_noise: 0.1
  policy_noise: 0.2
  noise_clip: 0.5
  policy_freq: 2
  start_timesteps: 25000
  batch_size: 4
  latest_step: null
  latest_rl_step: null

ritp_planner_feature_params:
  _target_: nuplan_zigned.training.modeling.models.ritp_planner.RITPPlannerFeatureParams
  _convert_: 'all'
  # feature params
  radius: 300
  map_features: [LANE, LEFT_BOUNDARY, RIGHT_BOUNDARY, STOP_LINE, CROSSWALK, ROUTE_LANES]
  max_elements:
    LANE: null
    LEFT_BOUNDARY: null
    RIGHT_BOUNDARY: null
    STOP_LINE: null
    CROSSWALK: null
    ROUTE_LANES: null
  max_points:
    LANE: 20
    LEFT_BOUNDARY: 20
    RIGHT_BOUNDARY: 20
    STOP_LINE: 20
    CROSSWALK: 20
    ROUTE_LANES: 20
  agent_features: [VEHICLE, PEDESTRIAN, BICYCLE, TRAFFIC_CONE, BARRIER, CZONE_SIGN, GENERIC_OBJECT]
  max_agents:
    VEHICLE: null
    PEDESTRIAN: null
    BICYCLE: null
    TRAFFIC_CONE: null
    BARRIER: null
    CZONE_SIGN: null
    GENERIC_OBJECT: 10
  interpolation_method: linear
  num_past_steps: ${model.ritp_planner_feature_params.past_trajectory_sampling.num_poses}
  num_future_steps: ${model.ritp_planner_feature_params.future_trajectory_sampling.num_poses}
  past_trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    num_poses: 49      # target past poses
    time_horizon: 4.9  # [s] time horizon of pase poses
  future_trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    num_poses: 80     # target future poses
    time_horizon: 8.  # [s] time horizon of future poses


# ----------qcmae params----------
qcmae_model_params:
  _target_: nuplan_zigned.training.modeling.models.ritp_planner.QCMAEModelParams
  _convert_: 'all'
  input_dim: 2
  hidden_dim: 64
  output_dim: 2
  output_head: False  # whether the model output heading. if False, heading will be estimated by arctan(dy/dx)
  num_past_steps: ${model.qcmae_feature_params.past_trajectory_sampling.num_poses}
  num_future_steps: ${model.qcmae_target_params.future_trajectory_sampling.num_poses}
  num_modes: 6
  num_recurrent_steps: 4
  num_freq_bands: 64
  num_map_layers: 1
  num_agent_layers: 1
  num_dec_layers: 1
  num_heads: 8
  head_dim: 16
  dropout: 0.1
  pl2pl_radius: 150
  time_span: 10
  pl2a_radius: 50
  a2a_radius: 50
  num_t2m_steps: 30
  pl2m_radius: 150
  a2m_radius: 15
  pretrained_model_dir: null

qcmae_feature_params:
  _target_: nuplan_zigned.training.modeling.models.ritp_planner.QCMAEFeatureParams
  _convert_: 'all'
  # Map features
  dim: 3
  num_past_steps: ${model.qcmae_feature_params.past_trajectory_sampling.num_poses}
  num_future_steps: ${model.qcmae_target_params.future_trajectory_sampling.num_poses}
  radius: 150
  map_features: [LANE, LEFT_BOUNDARY, RIGHT_BOUNDARY, STOP_LINE, CROSSWALK, ROUTE_LANES]
  max_elements:
    LANE: 30
    LEFT_BOUNDARY: 30
    RIGHT_BOUNDARY: 30
    STOP_LINE: 20
    CROSSWALK: 20
    ROUTE_LANES: 30
  max_points:
    LANE: 20
    LEFT_BOUNDARY: 20
    RIGHT_BOUNDARY: 20
    STOP_LINE: 20
    CROSSWALK: 20
    ROUTE_LANES: 20
  predict_unseen_agents: False
  vector_repr: True
  interpolation_method: linear
  # Agent features
  agent_features: [VEHICLE, PEDESTRIAN, BICYCLE, TRAFFIC_CONE, BARRIER, CZONE_SIGN, GENERIC_OBJECT]
  max_agents:
    VEHICLE: 30
    PEDESTRIAN: 30
    BICYCLE: 30
    TRAFFIC_CONE: 30
    BARRIER: 30
    CZONE_SIGN: 30
    GENERIC_OBJECT: 10
  # Parameters for past trajectory
  past_trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    num_poses: 49      # target past poses
    time_horizon: 4.9  # [s] time horizon of past poses

qcmae_target_params:
  _target_: nuplan_zigned.training.modeling.models.ritp_planner.QCMAETargetParams
  _convert_: 'all'
  agent_featrues: [VEHICLE, PEDESTRIAN, BICYCLE]
  num_past_steps: ${model.qcmae_feature_params.past_trajectory_sampling.num_poses}
  # Parameters for predicted trajectory
  future_trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    num_poses: 80      # target future poses
    time_horizon: 8.0  # [s] time horizon of future poses

# ----------rewardformer params----------
rewardformer_model_params:
  _target_: nuplan_zigned.training.modeling.models.ritp_planner.RewardFormerModelParams
  _convert_: 'all'
  dropout: 0.1
  sigma_prior: 1.
  precision_tau: 1.
  input_dim: 2
  hidden_dim: 64
  num_freq_bands: 64
  num_layers: 1
  num_heads: 8
  head_dim: 16
  gated_attention: true
  gate_has_dropout: false
  only_ego_attends_map: false
  num_samples: 10
  lambda_u_r: 1.5
  model_dir: null
  u_r_stats_dir: null

# Params for features
rewardformer_feature_params:
  _target_: nuplan_zigned.training.modeling.models.ritp_planner.RewardFormerFeatureParams
  _convert_: 'all'
  feature_types:
    NONE: -1
    EGO: 0
    VEHICLE: 1
    BICYCLE: 2
    PEDESTRIAN: 3
    LANE: 4
    STOP_LINE: 5
    CROSSWALK: 6
    LEFT_BOUNDARY: 7
    RIGHT_BOUNDARY: 8
    ROUTE_LANES: 9
    TRAFFIC_CONE: 10
    BARRIER: 11
    CZONE_SIGN: 12
    GENERIC_OBJECT: 13
  total_max_points: 20
  feature_dimension: 8
  # Agent features
  agent_features: [VEHICLE, PEDESTRIAN, BICYCLE, TRAFFIC_CONE, BARRIER, CZONE_SIGN, GENERIC_OBJECT]
  ego_dimension: 3
  agent_dimension: 8
  max_agents:
    VEHICLE: 30
    PEDESTRIAN: 30
    BICYCLE: 30
    TRAFFIC_CONE: 30
    BARRIER: 30
    CZONE_SIGN: 30
    GENERIC_OBJECT: 10
  # Map features
  map_features: [LANE, LEFT_BOUNDARY, RIGHT_BOUNDARY, STOP_LINE, CROSSWALK, ROUTE_LANES]
  max_elements:
    LANE: 20
    LEFT_BOUNDARY: 20
    RIGHT_BOUNDARY: 20
    STOP_LINE: 10
    CROSSWALK: 10
    ROUTE_LANES: 20
  max_points:
    LANE: 10
    LEFT_BOUNDARY: 10
    RIGHT_BOUNDARY: 10
    STOP_LINE: 10
    CROSSWALK: 10
    ROUTE_LANES: 10
  vector_set_map_feature_radius: 20    # [m] The query radius scope relative to the current ego-pose.
  interpolation_method: linear
  disable_map: False
  disable_agents: False

  num_poses: 20      # number of poses in trajectory in addition to initial state
  time_horizon: ${model.qcmae_target_params.future_trajectory_sampling.time_horizon}  # [s] time horizon of all poses
  frenet_radius: 100.0    # [m] The minimum query radius scope relative to the current ego-pose. Used when building Frenet frame. Will be adjusted according to speed.
