# @package _global_
job_name: train_avrl_vector
py_func: train
objective_aggregate_mode: mean

defaults:
  - override /data_augmentation:
  - override /objective:
      - elbo_objective
  - override /splitter: nuplan
  - override /model: avrl_vector_model
  - override /scenario_filter: training_scenarios
  - override /training_metric:
      - avg_displacement_error
      - avg_heading_error
      - final_displacement_error
      - final_heading_error
